# Generated by Django 5.0.4 on 2024-06-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='price_end',
            new_name='from_value',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='price_start',
            new_name='start_value',
        ),
    ]
