# Generated by Django 5.0.4 on 2024-06-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_price_end_contact_from_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='type',
            new_name='service',
        ),
    ]
