# Generated by Django 5.0.4 on 2024-06-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_type_contact_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='start_value',
            new_name='to_value',
        ),
    ]
